import RootProvider from "@/providers/RootProvider";
import GlobalStyles from "@/theme/globals";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <RootProvider>
          {GlobalStyles}
          {children}
        </RootProvider>
      </body>
    </html>
  );
}
